name: CMake Multi-Platform Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-linux:
    name: Build (Linux)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
        build_type: [Release]
    steps:
      - uses: actions/checkout@v4
      - name: Set up compilers
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ clang
      - name: Configure
        run: >
          cmake -B build
          -DCMAKE_CXX_COMPILER=${{ matrix.compiler == 'gcc' && 'g++' || 'clang++' }}
          -DCMAKE_C_COMPILER=${{ matrix.compiler == 'gcc' && 'gcc' || 'clang' }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -S .
      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }}
      - name: Test
        run: ctest --test-dir build --output-on-failure

  build-macos:
    name: Build (macOS)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: >
          cmake -B build
          -DCMAKE_BUILD_TYPE=Release
          -S .
      - name: Build
        run: cmake --build build --config Release
      - name: Test
        run: ctest --test-dir build --output-on-failure

  build-windows:
    name: Build (Windows)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: >
          cmake -B build
          -G "Visual Studio 17 2022"
          -A x64
          -DCMAKE_BUILD_TYPE=Release
          -S .
      - name: Build
        run: cmake --build build --config Release
      - name: Test
        run: ctest --test-dir build --build-config Release --output-on-failure
